name: Build Example App

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}

    strategy:
      fail-fast: false
      matrix:
        variant: [debug, release]
        include:
          - variant: debug
            artifact-path: build/app/outputs/apk/app-debug.apk
          - variant: release
            artifact-path: build/app/outputs/flutter-apk/app-release.apk

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true
    - run: dart pub get
    - run: dart format --output=none --set-exit-if-changed .
    - run: dart analyze
    - run: flutter pub get
      working-directory: example/
    #- run: flutter test
    - run: flutter build apk --debug --verbose
      working-directory: example/
    - uses: actions/upload-artifact@v4
      with:
        name: example-apk-${{ matrix.variant }}
        path: example/${{ matrix.artifact-path }}
